# This is a basic workflow to help you get started with Actions

name: Build Resume and Upload

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
      env:
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}   
    - name: Get Resume File
      run: |-
          gsutil cp gs://$GCS_BUCKET/resume/data.yml ./resume/data.yml
      env:
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}   
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm run export

    - name: Deploy
      run: |-
          gsutil cp pdf/material-dark.pdf gs://$GCS_BUCKET/resume/pdfexport/resume.pdf
      env:
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}   
